himaya/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from himaya.views import *

app_name='himaya'

urlpatterns = [
    path('',views.home, name='home'),

    

    url(r'^urais_mikoa/$', views.urais_mikoa, name = 'urais_mikoa'),
    url(r'^urais_nchi/$', views.urais_nchi, name = 'urais_nchi'),
    url(r'^announcement/$', views.announcement, name = 'announcement'),


    url(r'^regions/$', views.regions, name= 'regions'),
    url(r'^get_regional_votes_geo/$', views.get_regional_votes_geo, name= 'get_regional_votes_geo'),

    url(r'^get_pres_votes_Geo/$', views.get_pres_votes_Geo, name= 'get_pres_votes_Geo'),
    url(r'^regcenter/$', views.regcenter, name= 'regcenter'),

    url(r'^districts/$', views.districts, name= 'districts'), 
    url(r'^constituency/$', views.constituency, name= 'constituency'), 
    url(r'^wards/$', views.wards, name= 'wards'),
    
    url(r'^wards_in_constituency/$', views.wards_in_constituency, name= 'wards_in_constituency'),
    url(r'^get_constituencies/$', views.get_constituencies, name= 'get_constituencies'),
    url(r'^get_R_constituency/$', views.get_R_constituency, name= 'get_R_constituency'),
    url(r'^get_C_wards/$', views.get_C_wards, name= 'get_C_wards'),
    
    url(r'^get_constituency/$', views.get_constituency, name= 'get_constituency'),
    
    url(r'^get_Const_Winners/$', views.get_Const_Winners, name= 'get_Const_Winners'),
    url(r'^get_C_wards_Winners/$', views.get_C_wards_Winners, name= 'get_C_wards_Winners'),
    url(r'^get_C_wards_View/$', views.get_C_wards_View, name= 'get_C_wards_View'),

    url(r'^get_R_constituency_View/$', views.get_R_constituency_View, name= 'get_R_constituency_View'),
    url(r'^get_R_village_View/$', views.get_R_village_View, name= 'get_R_village_View'),

    
    url(r'^PresVotesConst/$', views.PresVotesConst, name= 'PresVotesConst'),
     url(r'^get_presidential_const_votes_total/$', views.get_presidential_const_votes_total, name= 'get_presidential_const_votes_total'),


    # url(r'^tanzania/$', views.tanzania, name= 'tanzania'), 

    # url(r'^necgis/$', GisPageView.as_view(), name = 'necgis'),

    # url(r'^results/$', ResultsPageView.as_view(), name = 'results'),


    # url(r'^urais/$', UraisView.as_view(), name = 'urais'),
    # url(r'^ubunge/$', UbungeView.as_view(), name = 'ubunge'),


    # url(r'^between/$', BetweenAd.as_view(), name = "between"),
    # url(r'^othermaps/$', othermaps.as_view(), name = "othermaps"),

    # url(r'^region_data/$', region_datasets, name = 'region_data'),
    # url(r'^regcenter_data/$', regcenter_datasets, name = 'regcenter_data'),



    
    
      
]

home/urls.py






from django.conf.urls import url
from django.urls import path, re_path
from . import views
from home.views import HomeView

app_name='home'

urlpatterns = [

    path('', views.index),
    
    
    path('chat', HomeView.as_view(), name = 'chat'),
    
    path('home/', views.home, name = "home"),
    path('index/', views.index, name = "index"), 
 
    
    re_path(r'^item/(?P<item_id>\d+)/$', views.item, name = "item"),
    re_path(r'^item/(?P<item_id>\d+)/book/$', views.book, name = "book"),
    re_path(r'^item/(?P<item_id>\d+)/payment/$', views.payment, name = "payment"),
    re_path(r'^item/(?P<item_id>\d+)/donate/$', views.donate, name = "donate"),
    


    path('activate/', views.activate, name = "activate"),
    path('activatefriend/', views.activatefriend, name = "activatefriend"),

    path('makala/', views.makala, name = "makala"),
    path('authors/', views.authors, name = "authors"),
    

    re_path(r'^category/(?P<category_id>\d+)/$', views.category, name = "category"),

    path('hasira/', views.hasira, name = "hasira"),
    path('gis/', views.gis, name = "gis"),
    path('myrefference/', views.myrefference, name = "myrefference"),

    path('gispay/', views.gispay, name = "gispay"),
    path('bitcoin/', views.bitcoin, name = "bitcoin"),
    path('matangazo/', views.matangazo, name = "matangazo"),
    path('mahesabu/', views.mahesabu, name = "mahesabu"),
    path('uaminifu/', views.uaminifu, name = "uaminifu"),
    path('english_book/', views.english_book, name = "english_book"),
    path('lulu_book/', views.lulu_book, name = "lulu_book"),
    path('gis_project/', views.gis_project, name = "gis_project"),
    path('wito/', views.wito, name = "wito"),
    path('nisome_kabla/', views.nisome_kabla, name = "nisome_kabla"),
    


    path('register/', views.register, name = "register"),
    
      
]

mysite/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import  admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import ItemSitemap,ViewSitemap
from accounts.sitemaps import StaticViewSitemap
sitemaps = {
    
    'static': StaticViewSitemap,
    'view':ViewSitemap,
    'snippet': ItemSitemap,
}

app_name='mysite'

urlpatterns = [
     path('', views.login_redirect, name='login_redirect'),
    
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include ('accounts.urls',namespace='accounts')),
    path('home/', include ('home.urls', namespace='home')),
    path('himaya/', include ('himaya.urls', namespace='himaya')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)               
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views 
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import  admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import ItemSitemap,ViewSitemap
from accounts.sitemaps import StaticViewSitemap
sitemaps = {
    
    'static': StaticViewSitemap,
    'view':ViewSitemap,
    'snippet': ItemSitemap,
}

app_name='mysite'

urlpatterns = [
     path('', views.login_redirect, name='login_redirect'),
    
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include ('accounts.urls',namespace='accounts')),
    path('home/', include ('home.urls', namespace='home')),
    path('himaya/', include ('himaya.urls', namespace='himaya')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)               
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Post(models.Model):

    post = models.CharField(max_length=200)
    bookname = models.CharField (max_length=220, default='', blank=True)
    booklink = models.CharField (max_length=220, default='', blank=True)
    bookimage = models.ImageField(default='default.jpg', upload_to='media')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.username
  

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Category'
        
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return self.name

class Paymentdetail(models.Model):
    name = models.CharField (max_length=120, default='')
    
    def __str__(self):
        return self.name
    


class Item(models.Model):
    class Meta:
        verbose_name_plural = 'Item'
    
    name = models.CharField(max_length= 50)
    subtitle = models.CharField (max_length=120, default='', blank=True)
    description = models.TextField()
    image = models.ImageField(default='default.jpg', upload_to='media')
    
    image_author = models.ImageField(default='default.jpg', upload_to='media')
    

    image_index = models.ImageField(default='default.jpg', upload_to='media')
    
    videofile= models.FileField(default='default.mp4', upload_to='media', null=True, verbose_name="")

    author = models.CharField(max_length=200, default= "")
    author_description = models.TextField(default= "")
    price = models.IntegerField(default=0)
    tigopesa = models.IntegerField(default=0, blank=True)
    mpesa = models.IntegerField(default=0, blank=True)
    airtel = models.IntegerField(default=0, blank=True)
    halotel = models.IntegerField(default=0, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    paymentdetail = models.ForeignKey(Paymentdetail, null=True, on_delete=models.PROTECT)
    
    def __str__(self):
        return self.name + ": " + str(self.videofile)
    def get_absolute_url(self):
        return "/item/%i/" % self.pk
  





class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.current_user
    
    
    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

        
    
    def __str__(self):
        return str(self.current_user)

        
    # @classmethod
    # def lose_friend(cls, current_user, new_friend):
    #     friend, created = cls.objects.get_or_create(
    #         current_user=current_user
    #     )
    #     friend.users.remove(new_friend)
    

     
#This model is for class registration 
class Post4(models.Model):
    class Meta:
        verbose_name_plural = 'Students Request'
    
    fullname = models.CharField (max_length=100, default='')
    username = models.CharField (max_length=100, default='')
    country = models.CharField (max_length=100, default='')
    region = models.CharField (max_length=100, default='')
    Proffession = models.CharField (max_length=100, default='')
    book = models.CharField (max_length=250, default='')
    subtitle = models.CharField (max_length=100, default='')
    phone = models.IntegerField(default=0)
    Jina = models.CharField (max_length=100, default='')
    Simu = models.IntegerField(default=0)
    Tukusaidiaje = models.TextField(default='')
    
    
    
    def __str__(self):
        return self.fullname
    

himaya/forms.py
from django import forms



CHARACTER_ENCODINGS = [("ascii", "ASCII"),
 ("latin1", "Latin-1"), ("utf8", "UTF-8")]

class ImportShapefileForm(forms.Form):
	import_file = forms.FileField(label="Select a Zipped Shapefile")
	character_encoding = forms.ChoiceField(choices=CHARACTER_ENCODINGS, initial="utf8")

himaya/templates/himaya/announcement.html
<!DOCTYPE html>
<html lang="en">
{% load static %} 


<head>


 
    <title>Tanzania </title>

    <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

  
    <meta name="author" content="Overblessing Msuya" />
    <meta name="keywords" content="Web GIS,Live Map Data Update, Elections Live map, Live Map Update, leaflet-ajax-Django-postgis" />
 
    <meta name="theme-color" content="#ffffff">

      <link href="https://fonts.googleapis.com/css?family=Montserrat|Niramit" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">

    <link href="{% static 'accounts/leaflet/leaflet.css'%}" rel='stylesheet' />

    <link href="{% static 'accounts/scripts/styles.css' %}" rel='stylesheet' />
     <link href="{% static 'accounts/css/jquery-ui.css' %}" rel='stylesheet' />
    
  
  
  <link rel="stylesheet" href="{% static 'accounts/scripts/Control.FullScreen.css'%}" />
  
  <link rel="stylesheet" href="{% static 'accounts/scripts/easy-button.css' %}">

  <link rel="stylesheet" href="{% static 'accounts/css/app.css' %}">
</head>
<body>

 

<section class="f-section">
 
    

    <div class= "text-center">
<h2>COMMISSION</h2>

<h3><a href="#">2020</a></h3>

 <h2 id="regname"></h2> 
</div>
    <div class="row" >


            <div class="col-md-10">

             
              <div id="map"></div>

            </div>

            <div class="col-md-2">

              <div id="sidebar" class="mt-8">
                    
                               
                    <ul class="nav nav-tabs">
                      
                      <li><a data-toggle="tab" href="#regiond">Search</a></li>
                      <li><a data-toggle="tab" href="#test">Colour</a></li> 

                      
                    </ul>

                  <div class="tab-content">
                    
                    <div id="test" class="tab-pane">
                       
                       
                        <table class="table">
                          <thead>
                            <tr>
                              
                              <th scope="col">Symbol</th>
                              <th scope="col">Name</th>
                              
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              
                              <td><div class="bluecircle"></div></td>
                              <td>A</td>
                              
                            </tr>
                            <tr>
                             
                              <td><div class="purplecircle"></div></td>
                              <td>B</td>
                             
                            </tr>
                            <tr>
                             
                              <td><div class="greencircle"></div></td>
                              <td>C</td>
                              
                            </tr>
                            <tr>
                               
                                <td><div class="yellowcircle"></div></td>
                                <td>BD</td>
                                
                              </tr>
                        </tbody>
                       </table>
                    </div> 
                    
                 
                    <div id="regiond" class="tab-pane active">
                      
                     
                      {% csrf_token %}
                       
                      <h4 id="regname"></h4> 

                      <div class="form-group">
                        <label for="">
                          1.Region:
                        </label>
                        <select name="selectregion" class="form-control" id="selectregion"></select> 
                      </div>
                         

                      <div id="con">
                        <div class="form-group">
                          <label for="">
                             2.Cons:
                          </label>
                           <select name="selectconstituent" id="selectconstituent" class="form-control"></select>  
                        </div>     
                      </div>


                     

                      <div  id="errordiv" class="alert alert-danger" role="alert"></div>

                      {% csrf_token %}

                      <div id="resultsdiv"></div>
                    </div>
                        
                  </div>                    
                                    
              </div> 
            </div>  

    </div>


</section>


          

        <script src="{% static 'accounts/js/jquery-3.4.1.min.js' %}"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <!--<script src="{% static 'accounts/js/bootstrap.min.js' %}"></script>-->

        <!-- Latest compiled and minified JavaScript -->
<script src="{% static 'accounts/js/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'accounts/js/bootstrap.min.js' %}" type="text/javascript"></script>

        <script src="{% static 'accounts/leaflet/leaflet.js' %}"></script>
        <!-- <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
   integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
   crossorigin=""></script> -->
        
        <script src="{% static 'accounts/scripts/Control.FullScreen.js' %}"></script>
    
        <!--<script src="{% static 'accounts/scripts/L.Control.Locate.min.js' %}"></script>-->
        <script src="{% static 'accounts/scripts/african_names.js' %}"></script>
        <script src="{% static 'accounts/scripts/mapping.js' %}"></script>
        <!-- <script src="{% static 'accounts/scripts/forms_validate.js' %}"></script> -->



        

</body>
</html>

himaya/templates/himaya/index.html
{% extends 'base2.html' %}

{% load staticfiles %}


   {% block body %}
        <br>  <br>  
        <section class="section">
	    <div class="container">
			<small>
							<span class="caps">Items</span>
						</small>
                        <div class="line-sep"></div>
                
              
			  <p>Hii ni listi ya vitabu vinavyopatikana OBG online. Bonyeza chaguo lako ili kupata maelezo zaidi.<p>
                          <p>Kuona listi ya vitabu ulivyokwisha lipia bonyeza hapa <a href="{% url 'home:chat'%}"><span>Vitabu vyangu</span></a></p>
		  
                <hr>
                <div class="row">
                     <div class="col-md-6">
                        
                        
                        
                       
						
                        
                        
                       {% for category in categories %}
                           
		    
                           <h3>{{category.name}}</h3>
                           
                           
                           {%for item in category.item_set.all %}
                              
                               <h3><a href="{% url 'himaya:item' item_id=item.id %}"> <ul> {{item.name}}</ul></a></h3>
                           
                           {%endfor%}
                        {%endfor%}
          
                    </div>
                </div>
            </div>
        </section>
        
        
     
      <br><br>
      
      


   {% endblock %}

himaya/templates/himaya/item.html
{% extends 'base3.html' %}
{% load staticfiles %}
    {%block head%}
     
    {% if item != None %}
        <title>{{item.name}}-Selected Class</title>
        
    {% else %}
        <title>Invalid Item ID- Selected Class</title>
    {% endif %}
    
    {%endblock%}


   {% block body %}


 <a href="{% url 'home:index' %}">&lt; Back to the list</a>
               
      
         
                      <div class="container">
                            <small><span class="caps">Book</span></small>
                            <div class="line-sep"></div>
                              
                                {% if item != None %}   
                                    
                                <div class="section-title">{{item.name}}</div>
                                    <hr>
                      </div>
                     
               
                
                                <section class="section grey-scale">
                     <div class="container">
                                        
                                <div class="row">
                                    <div class="col-md-7">
                                        <h3>Kwa ufupi</h3>
                                        <p>{{item.description}}</p>
                                    <h3>Cover</h3>
                                        {% if item.image%}
                                                <img src='{{item.image.url}}' class= 'img-responsive'/>
                                                
                                         {%endif%}
                                    
                                    </div><br>
                                   
                                    <div class="col-md-5">
					<h3>Bei Tsh {{item.price}} </h3>
					<div class="card right-in">
					    <div class="card-icon">
                                                <br><br>
						<ul class="tutor-icons">
                                                   
                                                    <br><br> 
						    
                                                    <h4><a class="btn btn-follow btn-lg "href="{% url 'home:chat'%}"> Nenda Kazini</a></h4>                                                   -->
                                                    
                                              
						</ul>
                                                    
                                                
                                                  <br>
                                                   <hr>
                                                  
                                            </div>
                                        </div>
                                    </div>      
                                {% else %}
                                                <p>Invalid Item ID.</p>
                                {% endif %}
                                                                
                              </div>
                    </div>
                </section>
                
      <br>
                
                <div class="container"
        <section class="section">
            
                 <small><span class="caps">Hasira Hasara</span></small>
                            <div class="line-sep"></div>
                
                 <div class="col-md-12">
						
                                                <div class="row">
                                                    <h1>Kuhusu Muandishi</h1>
							<!--<div class="col-md-5">-->
                                                            
								<div class="tutor">
                                                                    
									<div class="tutor-image">
										{% if item.image%}
										<img src='{{item.image_author.url}}' />
                                                                                {%endif%}
									</div>

									
                                                                        
                                                                        <div class="text-center">
										<h4>
											Overblessing A Msuya
										</h4>
										
                                                                                <hr>
									</div>

									
									    
								</div>
							</div>
                                                        
                                                        <!--<div class="col-md-6">-->
                                                           
									

									<div class="text-left">
										<p>
										{{item.author_description}}
											
                                                                                        
										</p>
										
                                                                             
									</div>

									
							</div>


        </section>
        
      </div>
           <hr>
            
            <br><br>




   {% endblock %}

himaya/templates/himaya/urais_nchi.html
<!DOCTYPE html>
<html lang="en">
{% load static %} 


<head>

    <title>GIS</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="author" content="Overblessing Msuya" />
    <meta name="keywords" content="Web GIS,Live Map Data Update, Elections Live map, Live Map Update, leaflet-ajax-Django-postgis" />
    <meta name="theme-color" content="#ffffff">

    <link href="https://fonts.googleapis.com/css?family=Montserrat|Niramit" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'accounts/css/bootstrap.min.css' %}">
    <link href="{% static 'accounts/leaflet/leaflet.css'%}" rel='stylesheet' />
    <link href="{% static 'accounts/scripts/styles.css' %}" rel='stylesheet' />
    <link href="{% static 'accounts/css/jquery-ui.css' %}" rel='stylesheet' />
    <link rel="stylesheet" href="{% static 'accounts/scripts/Control.FullScreen.css'%}" />
    <link rel="stylesheet" href="{% static 'accounts/scripts/easy-button.css' %}">
</head>
<body>

    <div class="container-fluid">
     
    <div id="wrap">



        

<hr>

<h4 id="regname"></h4> 

  <div class="row" >


        <div class="col-sm-8">
                    <div id="map"></div>
        </div>

                <div id="sidebar" class="col-sm-4">
				
                
    <ul class="nav nav-tabs">  
      <li class="active"><a data-toggle="tab" href="#homeD">Legend</a></li>
      <li class="active"><a data-toggle="tab" href="#regiond">Find Region</a></li>
    </ul>

  <div class="tab-content">
          <div id="homeD" class="tab-pane active">
                  <div id="chartContainer2" style="height: 300px; width: 100%;"></div>
                  <div id="chartContainer" style="height: 200px; width: 100%;"></div>
          </div>
          
 
    <div id="regiond" class="tab-pane fade in active">          
                    <br>           
                  {% csrf_token %}
                                 1.Region: <br>
                                  <h6> Click on a region in the map to select it <br>Or </h6>
                                  <h6> Select from a List </h6>
                                <h4 id="regname"></h4> 
                             1.Region: <br>
                            <select name="selectregion" id="selectregion"></select>  
                                <br>
                                <div id="con">
                                      2.Constituency:<br>
                                        <select name="selectconstituent" id="selectconstituent"></select>   
                                </div>
                                <div id="wd">   
                                      3.Ward:<br>
                                        <select name ="selectwards" id="selectwards"></select>       
                                  </div>    
                 {% csrf_token %}

                    <div id="resultsdiv"></div>
</div>    
</div>                                          
</div>             
                </div>
            </div>
</div> <!--wrapper-->
   

     

        <script src="{% static 'accounts/js/jquery-3.4.1.min.js' %}"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        
        <script src="{% static 'accounts/js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'accounts/leaflet/leaflet.js' %}"></script>
       
        <script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
        <script src="{% static 'accounts/scripts/Control.FullScreen.js' %}"></script>
		
	      
		    <script src="{% static 'accounts/scripts/african_names.js' %}"></script>
		    <script src="{% static 'accounts/scripts/presidential.js' %}"></script>
        <script src="{% static 'accounts/scripts/forms_validate.js' %}"></script>


      

</body>
</html>