home/urls.py






from django.conf.urls import url
from django.urls import path, re_path
from . import views
from home.views import HomeView

app_name='home'

urlpatterns = [

    path('', views.index),
    
    
    path('chat', HomeView.as_view(), name = 'chat'),
    
    path('home/', views.home, name = "home"),
    path('index/', views.index, name = "index"), 
 
    
    re_path(r'^item/(?P<item_id>\d+)/$', views.item, name = "item"),
    re_path(r'^item/(?P<item_id>\d+)/book/$', views.book, name = "book"),
    re_path(r'^item/(?P<item_id>\d+)/payment/$', views.payment, name = "payment"),
    re_path(r'^item/(?P<item_id>\d+)/donate/$', views.donate, name = "donate"),
    


    path('activate/', views.activate, name = "activate"),
    path('activatefriend/', views.activatefriend, name = "activatefriend"),

    path('makala/', views.makala, name = "makala"),
    path('authors/', views.authors, name = "authors"),
    

    re_path(r'^category/(?P<category_id>\d+)/$', views.category, name = "category"),

    path('hasira/', views.hasira, name = "hasira"),
    path('gis/', views.gis, name = "gis"),
    path('myrefference/', views.myrefference, name = "myrefference"),

    path('gispay/', views.gispay, name = "gispay"),
    path('bitcoin/', views.bitcoin, name = "bitcoin"),
    path('matangazo/', views.matangazo, name = "matangazo"),
    path('mahesabu/', views.mahesabu, name = "mahesabu"),
    path('uaminifu/', views.uaminifu, name = "uaminifu"),
    path('english_book/', views.english_book, name = "english_book"),
    path('lulu_book/', views.lulu_book, name = "lulu_book"),
    path('gis_project/', views.gis_project, name = "gis_project"),
    path('wito/', views.wito, name = "wito"),
    path('nisome_kabla/', views.nisome_kabla, name = "nisome_kabla"),
    


    path('register/', views.register, name = "register"),
    
      
]

mysite/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import  admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import ItemSitemap,ViewSitemap
from accounts.sitemaps import StaticViewSitemap
sitemaps = {
    
    'static': StaticViewSitemap,
    'view':ViewSitemap,
    'snippet': ItemSitemap,
}

app_name='mysite'

urlpatterns = [
     path('', views.login_redirect, name='login_redirect'),
    
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include ('accounts.urls',namespace='accounts')),
    path('home/', include ('home.urls', namespace='home')),
    path('himaya/', include ('himaya.urls', namespace='himaya')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)               
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views 
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import  admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import ItemSitemap,ViewSitemap
from accounts.sitemaps import StaticViewSitemap
sitemaps = {
    
    'static': StaticViewSitemap,
    'view':ViewSitemap,
    'snippet': ItemSitemap,
}

app_name='mysite'

urlpatterns = [
     path('', views.login_redirect, name='login_redirect'),
    
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include ('accounts.urls',namespace='accounts')),
    path('home/', include ('home.urls', namespace='home')),
    path('himaya/', include ('himaya.urls', namespace='himaya')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)               
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Post(models.Model):

    post = models.CharField(max_length=200)
    bookname = models.CharField (max_length=220, default='', blank=True)
    booklink = models.CharField (max_length=220, default='', blank=True)
    bookimage = models.ImageField(default='default.jpg', upload_to='media')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.username
  

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Category'
        
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return self.name

class Paymentdetail(models.Model):
    name = models.CharField (max_length=120, default='')
    
    def __str__(self):
        return self.name
    


class Item(models.Model):
    class Meta:
        verbose_name_plural = 'Item'
    
    name = models.CharField(max_length= 50)
    subtitle = models.CharField (max_length=120, default='', blank=True)
    description = models.TextField()
    image = models.ImageField(default='default.jpg', upload_to='media')
    
    image_author = models.ImageField(default='default.jpg', upload_to='media')
    

    image_index = models.ImageField(default='default.jpg', upload_to='media')
    
    videofile= models.FileField(default='default.mp4', upload_to='media', null=True, verbose_name="")

    author = models.CharField(max_length=200, default= "")
    author_description = models.TextField(default= "")
    price = models.IntegerField(default=0)
    tigopesa = models.IntegerField(default=0, blank=True)
    mpesa = models.IntegerField(default=0, blank=True)
    airtel = models.IntegerField(default=0, blank=True)
    halotel = models.IntegerField(default=0, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    paymentdetail = models.ForeignKey(Paymentdetail, null=True, on_delete=models.PROTECT)
    
    def __str__(self):
        return self.name + ": " + str(self.videofile)
    def get_absolute_url(self):
        return "/item/%i/" % self.pk
  





class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.current_user
    
    
    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

        
    
    def __str__(self):
        return str(self.current_user)

        
    # @classmethod
    # def lose_friend(cls, current_user, new_friend):
    #     friend, created = cls.objects.get_or_create(
    #         current_user=current_user
    #     )
    #     friend.users.remove(new_friend)
    

     
#This model is for class registration 
class Post4(models.Model):
    class Meta:
        verbose_name_plural = 'Students Request'
    
    fullname = models.CharField (max_length=100, default='')
    username = models.CharField (max_length=100, default='')
    country = models.CharField (max_length=100, default='')
    region = models.CharField (max_length=100, default='')
    Proffession = models.CharField (max_length=100, default='')
    book = models.CharField (max_length=250, default='')
    subtitle = models.CharField (max_length=100, default='')
    phone = models.IntegerField(default=0)
    Jina = models.CharField (max_length=100, default='')
    Simu = models.IntegerField(default=0)
    Tukusaidiaje = models.TextField(default='')
    
    
    
    def __str__(self):
        return self.fullname
    

home/forms.py
from django import forms
from home.models import Post
from home.models import Post4
from home.models import Friend




class HomeForm(forms.ModelForm):
    post= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Put book link....'
        }
    ))
    class Meta:
        model = Post
        fields=('user','post', 'bookname')
        
class FriendForm(forms.ModelForm):
    
    class Meta:
        model = Friend
        fields=('users', 'current_user')        
        
        
class ClassRegistration(forms.ModelForm):
    fullname= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Your first and last name....'
        }
    ))
    
    
   
    
    username= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Your login name created previously....'
        }
    ))
    
    region= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Your region or state ....'
        }
    ))
    

    class Meta:
        model = Post4
        fields = ('fullname', 'username','country', 'region','phone')

class PostForm2(forms.ModelForm):

    fullname= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Weka hapa jina lako la kwanza na la mwisho....'
        }
    ))

    book= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Weka hapa jina la kitabu unachokitaka kununu ....'
        }
    ))



    class Meta:
        model = Post4
        fields= [
            "fullname",
            "book",   
            
        ]
        
        
        

home/views.py
from django.shortcuts import render, redirect,reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.template import loader


from home.forms import HomeForm, ClassRegistration, PostForm2, FriendForm
from home.models import Post,Item, Category,Post4, Friend, Paymentdetail
from django.contrib.auth.decorators import login_required

#These class views is for chating
    
class HomeView(TemplateView):
    template_name ='home/chat.html'
        
    def get(self, request):
        form =HomeForm()
        posts = Post.objects.all().order_by('created')
        users = User.objects.all()
        #exclude(id=request.user.id)
    
        friend = Friend.objects.get(current_user=request.user)
    
        friends = friend.users.all()
      
        args = {'form': form, 'posts': posts, 'users': users, 'friends':friends}
        #'friends':friends
        return render(request, self.template_name, args)
        
    def post(self,request):
        form =HomeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.user =request.user
            post.save()
            text = form.cleaned_data['post']
            
            
            form = HomeForm()
            return redirect('home:chat')
            
        args = {'form': form, 'text':text}
        return render(request, self.template_name, args)
        
@login_required
def activate(request):
        form = HomeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            create = form.save()
            create.save
            
            return redirect('home:activatefriend')
            
        args = {'form': form}
        return render(request, 'home/activate.html', args)
@login_required
def activatefriend(request):
        form = FriendForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            create = form.save()
            create.save
            
            return redirect('home:authors')
            
        args = {'form': form}
        return render(request, 'home/activatefriend.html', args)



def home(request):
    context = {
       'categories':Item.objects.all() 
    }
    return render (request, "home/home.html", context)
 
def index(request):
    
    context = {
       'categories':Category.objects.all() 
    }
    return render(request, 'home/index.html', context)



def donate(request, item_id):
    try:
        itm = Item.objects.get(id=item_id)
    except Item.DoesNotExist:
        itm = None
        
    context = {
        'item': itm
    }

    return render (request, "home/donate.html", context)

def item(request, item_id):
    try:
        itm = Item.objects.get(id=item_id)
    except Item.DoesNotExist:
        itm = None
        
    context = {
        'item': itm
    }
    return render(request, 'home/item.html', context)

def category(request, category_id):
    try:
        catg = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        catg = None
    context = {
        'category': catg,
        'categories': Category.objects.all(),
        'count': Item.objects.filter(category=category_id).count()
    }
    return render(request, 'home/category.html', context)





#This view is for class registration- 
def register(request):
        form = ClassRegistration(request.POST or None)
        if form.is_valid():
            create = form.save()
            create.save
            
            return redirect('login')
            
        args = {'form': form}
        return render(request, 'home/create.html', args)
        
@login_required
def book(request, item_id):
    form = PostForm2(request.POST or None, request.FILES or None)
   
    if form.is_valid():
        create = form.save(commit=False)
        create.save()
            
        return redirect('home:payment', item_id)
            
    item = {'form': form}
        
    return render(request, 'home/book_request.html', item)

@login_required
def payment(request, item_id):
    try:
        itm = Item.objects.get(id=item_id)
    except Item.DoesNotExist:
        itm = None
        
    context = {'item': itm}

    return render (request, "home/payment.html", context)

def authors(request):
    return render (request, "home/authors.html", {})



def hasira(request):
    return render (request, "home/hasira.html", {})
def gis(request):
    return render (request, "home/gis.html", {})

def gispay(request):
    return render (request, "home/gispay.html", {})
def makala(request):
    return render (request, "home/makala.html", {})
@login_required
def bitcoin(request):
    return render (request, "home/bitcoin.html", {})

def matangazo(request):
    return render (request, "home/matangazo.html", {})
def mahesabu(request):
    return render (request, "home/mahesabu.html", {})

def uaminifu(request):
    return render (request, "home/uaminifu.html", {})
@login_required
def wito(request):
    return render (request, "home/wito.html", {})
@login_required
def english_book(request):
    return render (request, "home/english_intro.html", {})
@login_required
def lulu_book(request):
    return render (request, "home/lulu_book.html", {})

def gis_project(request):
    return render (request, "home/gis_project.html", {})
def nisome_kabla(request):
    return render (request, "home/nisome_kabla.html", {})
def myrefference(request):
    return render (request, "home/myrefference.html", {})




















#post_list      

     

home/templates/home/authors.html
<!DOCTYPE html>
<html lang="en">
    
{% extends 'base2.html' %}
{% load static %}

{%block head%}
     
    
    
    {%endblock%}



 {% block body %}

    <main class="main-wrapper">
        
        <aside class="left-sidebar">
           

             <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav" class="top-ul">                       
                        <!-- <li class="nav-small-cap">MENU</li>
                        <li><a href="" class="active">WEBSITE</a>  
                             -->
                            
                       
            
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
             </div>
                
    
                
        </aside>
  
    <div class="main-section">
        



        <div class="container">




            <div class="row">




                <div class="col-md-4">


    

        <h2>
                                           
                                        <span class="caps"><a class="btn btn-info "href="{% url 'home:chat'%}" role="button">VITABU VYANGU &raquo;</a></span>
                                        </h2>
                
                        
                                                <div class="line-sep"></div>
<p> Bonyeza Vitabu vyangu hapo juu kufungua Ofisi yako uweze kuona na kusoma vitabu ulivyokwisha nunua(online books). <span>Kama bado haujanunua kitabu chochote ukurasa huu hautafunguka.</span></p>
                    <!--<img src="{%static 'img/i.jpg'%}" class="img-responsive" alt=""'>   -->
                    <img src="{%static 'accounts/img/safront5.jpg'%}" class="img-responsive" alt=""'>   
                    


                    
      
                                        
                                        
                        
                                        
                                        
                       
</div>






<div class="col-md-4">


    

        
                
                         <span class="caps"><a class="btn btn-info "href="{% url 'accounts:index'%}" role="button">GIS &raquo;</a></span>
                                        </h2>
                                     <div class="line-sep"></div>   
<p> Soma GIS (Geographical Information Systeam) kwa njia ya mtandao kisha pata certificate yako, itakayokuwezesha kupata kazi mahala popote duniani.</p>
                    <!--<img src="{%static 'img/i.jpg'%}" class="img-responsive" alt=""'>   -->
                    <img src="{%static 'accounts/img/safront5.jpg'%}" class="img-responsive" alt=""'>   
                    
                                      
                       
</div>









<div class="col-md-4">


    

        
                
                      <span class="caps"><a class="btn btn-info "href="{% url 'accounts:index'%}" role="button">HIMAYA &raquo;</a></span>
                                                <div class="line-sep"></div>
<p> Je wewe ni mjasiriamali unayetamani kujenga imaya yako, tembelea ukurasa wetu huu hapo juu, utajifunza mengi na kupata fursa ya kibiashara. </p>
                    <!--<img src="{%static 'img/i.jpg'%}" class="img-responsive" alt=""'>   -->
                    <img src="{%static 'accounts/img/safront5.jpg'%}" class="img-responsive" alt=""'>   
                    


                    
      
                  
                                        
                                        
                        
</div>












</div>








<!-- Container -->
</div> 


        

    </div>                
            
        </main>
     
     
      {% endblock %}   
        
       

home/templates/home/home.html
{% extends 'base3.html' %}
{% load static %}
    {%block head%}
     
    {% if item != None %}
        <title>{{item.name}}-Selected Class</title>
        
    {% else %}
        <title>Invalid Item ID- Selected Class</title>
    {% endif %}
    
    {%endblock%}


   {% block body %}
	<!-- Added for Social Sharing -->
	<div class="a2a_kit a2a_kit_size_32 a2a_floating_style a2a_vertical_style" style="right:0px; top:147px; background-color: rgb(71, 107, 140);">
		<p class="share_to" style="font-size: 14px;"><span style="color: white;"><b>Share On</b></span></p>
		<a class="a2a_button_facebook" style="margin-top: -31px;" title="Share to Facebook"></a>
		<a class="a2a_button_twitter" title="Share to Twitter"></a>
		<a class="a2a_button_google_plus" title="Share to Google+"></a>
		<a class="a2a_button_linkedin" title="Share to Linkedin"></a>
	</div>
	<script async src="https://www.ciowhitepapersreview.com/assets/js/social_sharing.js"></script>	
<header>
		<nav class="navbar navbar-expand-lg navbar-light">

			<div class="container">
			  <button class="btn menu-btn d-md-none .d-lg-none"  onclick="openNav()">
			  	<i class="fa fa-bars"></i>
			  </button>

			  <a class="navbar-brand" href="#">OBG GLOBAL</a>
			
                            <div id="mySidenav" class="asidenav">
                              <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                              <a class="btn btn-follow href="{% url 'logout'%}" role="button">Logout </a>
                              <li class="nav-item mr-20"><a href="{% url 'login'%}">Log In</a></li>  
			      <a href="{% url 'home:chat'%}" role="button">My Books</a>
                               <a href="{% url 'accounts:register'%}" role="button">Register</a>
                              
                            </div>

			  <div class="collapse navbar-collapse" id="navbarSupportedContent">
			    <ul class="navbar-nav ml-auto">
			     	  {% if user.is_authenticated %}
                                
                                
                <li class="nav-item mr-20"><a href="{% url 'home:chat'%}">My Books</a></li>
                
                <li class="nav-item mr-20"><a class="btn btn-follow href="{% url 'logout'%}">Logout</a></li>
			    </ul>
                            
                      {%else%}         
                            
               <ul class="navbar-nav ml-auto">
                <!--<li class="nav-item mr-20"><a href="{% url 'home:home'%}">Home</a></li>-->
                 <li class="nav-item mr-20"><a href="{% url 'home:chat'%}">My Books</a></li>
                 <li class="nav-item mr-20"><a class="btn btn-follow href="{% url 'logout'%}">Logout</a></li>
		<li class="nav-item mr-20"><a href="{% url 'login'%}">Sign in</a></li>
                <a href="{% url 'accounts:register'%}" role="button">Register</a>
                <!--<li class="nav-item mr-20"><a href="{% url 'accounts:reset_password'%}">Reset Password</a></li>-->
            </ul>
            {%endif %}            
                            
                            
                            
                            
			  </div>
			</div>


		<div class="line"></div>
		</nav>
	</header>
                    
                
                    
                   

	<style>
.terms-home{
background: url(https://whatis.ciowhitepapersreview.com/border_diagonal.png) repeat-x 0 bottom;
}
.contnthere ul li {
	list-style-type : disc !important;
}
</style>
 
          <br> <br> 
	
        
        <section class="section grey-scale">
			<div class="container">
<div class="col-lg-12 col-md-12">
	<div class="col-lg-12 col-md-12" style="padding-left: 0;padding-right: 0;">
	
                 
 <h2 class="btn btn-follow" ><span><a href="{% url 'home:index'%}" style="color:#fff;text-decoration:none;">Nunua Vitabu</a></span></h2>
  <h2 class="btn btn-follow" ><span><a href="{% url 'home:authors'%}" style="color:#fff;text-decoration:none;">Kwa Waandishi wa Vitabu</a></span></h2>

  <button type="button" class="btn btn-follow" data-toggle="modal" data-target="#regprocess">Namna ya kununua kitabu
										</button> 
						</div>
					</div>
				<div class="course-image bottom-in">
								
<img src="{%static 'accounts/img/safront4.jpg'%}" class="img-responsive" alt=""'>	
								
						</div>
				
				
			</div>
        
        </section>
        
        
        
        
        <section id="vedio-sec" style="background-color: #fff;">
      
          <div class="container">
          
                                
					
<div class="col-lg-12 col-md-12  col-sm-12 contnthere" style="margin-bottom: 15px;">
							 <p style="text-align: justify;">
<p><span>OBG Company Limited</span> 

<p>Website hii inamilikiwa na kufanya kazi chini ya Kampuni ya "OBG Company Limited". Hii ni moja ya website chache maarufu nchini Tanzania ambayo inamuwezesha muandishi wa vitabu kuuza vitabu kwa njia ya mtandao (ebook) na msomaji kusoma vitabu mtandaoni. Website hii inawezesha watu wengi, haswa wale  wanaozungumza lugha ya Kiswahili, kupata vitabu na nakala mbali mbali kwa ajili ya kusoma kwa lengo la kujielimisha na kujiburudisha.</p>









</div></div></section>





							


<section class="section">
			<div class="container">
				<div class="row">

					<div class="col-md-12">
						
						<!-- <small><span class="caps"><a name="top"></a>Wasiliana nasi</span></small>
						
						<div class="line-sep"></div> -->
						<div class="section-title">
							
							<br>
							<p>Wasiliana Nasi.</p>
							<div class="line-sep"></div>
							

						</div>
					</div>
					<div class="col-md-7">
						<!--  <div class="tab">
		                          <button class="tablinks" onclick="openCity(event, 'contact')" id="defaultOpen">Contact</button>
		                </div> -->
                        
                                           
		                <div id="contact">
		                                
		                
		                    <div class="video-container">                                   
	 <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5233.185493903763!2d39.27138706048278!3d-6.833484473017059!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x185c4ba5bbc1ba7b%3A0x2f4f0a88e2089417!2sKariakoo%2C+Dar+es+Salaam!5e0!3m2!1sen!2stz!4v1538828227060" frameborder="0" style="border:0" allowfullscreen></iframe>
		                    </div>
		                    
		                </div>
					</div>

<br>
					<div class="col-md-5">
						<div class="">
		<div><p>Tupigie simu <a href="tel:0653397942" class="pull-right">+255653397942</a></p></div>
                        
	
                            <hr>
        <p class="text-center">Or <br> be classical</p>
                       
  <form>
  	<div class="form-group"><input type="text" class="form-control" name="" value="" placeholder="Name"></div>
                                                                
    <div class="form-group"><input type="email" class="form-control" name="" value="" placeholder="E-mail"></div>
                                                                
    <div class="form-group"><input type="tel" class="form-control" name="" value="" placeholder="Phone"></div>
                                                                
    <div class="form-group"><textarea class="form-control" name="" rows="3" placeholder="Message"></textarea></div>
                                                                
     <button class="btn btn-follow pull-right" type="submit" name="button">
           <i class="fa fa-paper-plane-o" aria-hidden="true"></i> Tuma</button>
  </form>
                        </div>
					</div>
				</div>
			</div>
		</section>
<br>
		 
	</main>




 <div class="modal fade bd-example-modal-lg" id="regprocess" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
        <div class="modal-header">
       <h5 class="modal-title" id="exampleModalLongTitle">Hatua za kununu kitabu</h5>
       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                
                                            <!--<div class="modal-body">-->
                                            
             <ul class="courses-lists " align="left">
                                            
           <li><p>1.Bonyeza nunua vitabu </p></li>
           <li><p>2. Kutoka kwenye listi ya vitabu, chagua kitabu unachokitaka kisha bonyeza kwenye picha ya kitabu.</p></li>
                                                
                                         
            <li><p>3. Maelezo ya kitabu husika yatafunguka, utaona maelezo ya kitabu kwa ufupi, utapata maelezo kuhusu muandishi, utapata video fupi pamoja na bei ya kitabu husika</p></li> 
                                                
          <li><p>5. Bonyeza neno lipa kupata kurasa ya malipo.Kama ni mara yako ya kwanza (haujawahi kusajiliwa) utapelekwa kwenye eneo la kujisajili kisha kujaza fomu kuonyesha kitabu unachokitaka. Kama umeshajisajili awali utapelekwa kwenye fomu kujaza taarifa za kitabu </p></li>
         <li><p>6.  Baada ya hapa utapatiwa taarifa za malipo kwenda kwa muandishi wa kitabu husika. Fanya malipo kisha subiri kitabu chako kufunguka.</p></li>
         <li><p>7. Baada ya muda mchache kitabu chako kitafunguka, ili kukiona na kuweza kukisoma utabonyeza neni vitabu vyangu.</p></li>
         <li><p>7. Kama utasubiri zaidi ya dakika kumi na tano bila kukiona kitabu basi wasiliana na muandishi kwa namba utakayoiona kwenye kurasa ya malipo.</p></li>
         
                                                </ul> 
                                               
                                                    
                                                
                                                    
                                                    
                                           
              
                            </div>
                        </div>
                    </div>


	

							
					
					
						
			</div>
		</div>
			
    </section>




    

	<script>
			function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
	</script>
 {% endblock %}

home/templates/home/letsee.html
hii

              
                  
                    {{category.name}}
                  
              
            