home/urls.py






from django.conf.urls import url
from django.urls import path, re_path
from . import views
from home.views import HomeView

app_name='home'

urlpatterns = [

    path('', views.index),
    
    
    path('chat', HomeView.as_view(), name = 'chat'),
    
    path('home/', views.home, name = "home"),
    path('index/', views.index, name = "index"), 
 
    
    re_path(r'^item/(?P<item_id>\d+)/$', views.item, name = "item"),
    re_path(r'^item/(?P<item_id>\d+)/book/$', views.book, name = "book"),
    re_path(r'^item/(?P<item_id>\d+)/payment/$', views.payment, name = "payment"),
    re_path(r'^item/(?P<item_id>\d+)/donate/$', views.donate, name = "donate"),
    


    path('activate/', views.activate, name = "activate"),
    path('activatefriend/', views.activatefriend, name = "activatefriend"),

    path('makala/', views.makala, name = "makala"),
    path('authors/', views.authors, name = "authors"),
    

    re_path(r'^category/(?P<category_id>\d+)/$', views.category, name = "category"),

    path('hasira/', views.hasira, name = "hasira"),
    path('gis/', views.gis, name = "gis"),
    path('myrefference/', views.myrefference, name = "myrefference"),

    path('gispay/', views.gispay, name = "gispay"),
    path('bitcoin/', views.bitcoin, name = "bitcoin"),
    path('matangazo/', views.matangazo, name = "matangazo"),
    path('mahesabu/', views.mahesabu, name = "mahesabu"),
    path('uaminifu/', views.uaminifu, name = "uaminifu"),
    path('english_book/', views.english_book, name = "english_book"),
    path('lulu_book/', views.lulu_book, name = "lulu_book"),
    path('gis_project/', views.gis_project, name = "gis_project"),
    path('wito/', views.wito, name = "wito"),
    path('nisome_kabla/', views.nisome_kabla, name = "nisome_kabla"),
    


    path('register/', views.register, name = "register"),
    
      
]

mysite/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import  admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import ItemSitemap,ViewSitemap
from accounts.sitemaps import StaticViewSitemap
sitemaps = {
    
    'static': StaticViewSitemap,
    'view':ViewSitemap,
    'snippet': ItemSitemap,
}

app_name='mysite'

urlpatterns = [
     path('', views.login_redirect, name='login_redirect'),
    
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include ('accounts.urls',namespace='accounts')),
    path('home/', include ('home.urls', namespace='home')),
    path('himaya/', include ('himaya.urls', namespace='himaya')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)               
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views 
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import  admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import ItemSitemap,ViewSitemap
from accounts.sitemaps import StaticViewSitemap
sitemaps = {
    
    'static': StaticViewSitemap,
    'view':ViewSitemap,
    'snippet': ItemSitemap,
}

app_name='mysite'

urlpatterns = [
     path('', views.login_redirect, name='login_redirect'),
    
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include ('accounts.urls',namespace='accounts')),
    path('home/', include ('home.urls', namespace='home')),
    path('himaya/', include ('himaya.urls', namespace='himaya')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)               
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Post(models.Model):

    post = models.CharField(max_length=200)
    bookname = models.CharField (max_length=220, default='', blank=True)
    booklink = models.CharField (max_length=220, default='', blank=True)
    bookimage = models.ImageField(default='default.jpg', upload_to='media')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.user.username
  

class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Category'
        
    name = models.CharField(max_length=32)
    
    def __str__(self):
        return self.name

class Paymentdetail(models.Model):
    name = models.CharField (max_length=120, default='')
    
    def __str__(self):
        return self.name
    


class Item(models.Model):
    class Meta:
        verbose_name_plural = 'Item'
    
    name = models.CharField(max_length= 50)
    subtitle = models.CharField (max_length=120, default='', blank=True)
    description = models.TextField()
    image = models.ImageField(default='default.jpg', upload_to='media')
    
    image_author = models.ImageField(default='default.jpg', upload_to='media')
    

    image_index = models.ImageField(default='default.jpg', upload_to='media')
    
    videofile= models.FileField(default='default.mp4', upload_to='media', null=True, verbose_name="")

    author = models.CharField(max_length=200, default= "")
    author_description = models.TextField(default= "")
    price = models.IntegerField(default=0)
    tigopesa = models.IntegerField(default=0, blank=True)
    mpesa = models.IntegerField(default=0, blank=True)
    airtel = models.IntegerField(default=0, blank=True)
    halotel = models.IntegerField(default=0, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    paymentdetail = models.ForeignKey(Paymentdetail, null=True, on_delete=models.PROTECT)
    
    def __str__(self):
        return self.name + ": " + str(self.videofile)
    def get_absolute_url(self):
        return "/item/%i/" % self.pk
  





class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, related_name='owner', null=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.current_user
    
    
    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user=current_user
        )
        friend.users.add(new_friend)

        
    
    def __str__(self):
        return str(self.current_user)

        
    # @classmethod
    # def lose_friend(cls, current_user, new_friend):
    #     friend, created = cls.objects.get_or_create(
    #         current_user=current_user
    #     )
    #     friend.users.remove(new_friend)
    

     
#This model is for class registration 
class Post4(models.Model):
    class Meta:
        verbose_name_plural = 'Students Request'
    
    fullname = models.CharField (max_length=100, default='')
    username = models.CharField (max_length=100, default='')
    country = models.CharField (max_length=100, default='')
    region = models.CharField (max_length=100, default='')
    Proffession = models.CharField (max_length=100, default='')
    book = models.CharField (max_length=250, default='')
    subtitle = models.CharField (max_length=100, default='')
    phone = models.IntegerField(default=0)
    Jina = models.CharField (max_length=100, default='')
    Simu = models.IntegerField(default=0)
    Tukusaidiaje = models.TextField(default='')
    
    
    
    def __str__(self):
        return self.fullname
    

home/forms.py
from django import forms
from home.models import Post
from home.models import Post4
from home.models import Friend




class HomeForm(forms.ModelForm):
    post= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Put book link....'
        }
    ))
    class Meta:
        model = Post
        fields=('user','post', 'bookname')
        
class FriendForm(forms.ModelForm):
    
    class Meta:
        model = Friend
        fields=('users', 'current_user')        
        
        
class ClassRegistration(forms.ModelForm):
    fullname= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Your first and last name....'
        }
    ))
    
    
   
    
    username= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Your login name created previously....'
        }
    ))
    
    region= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Your region or state ....'
        }
    ))
    

    class Meta:
        model = Post4
        fields = ('fullname', 'username','country', 'region','phone')

class PostForm2(forms.ModelForm):

    fullname= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Weka hapa jina lako la kwanza na la mwisho....'
        }
    ))

    book= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Weka hapa jina la kitabu unachokitaka kununu ....'
        }
    ))



    class Meta:
        model = Post4
        fields= [
            "fullname",
            "book",   
            
        ]
        
        
        

home/views.py
from django.shortcuts import render, redirect,reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView
from django.contrib.auth.models import User
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.template import loader


from home.forms import HomeForm, ClassRegistration, PostForm2, FriendForm
from home.models import Post,Item, Category,Post4, Friend, Paymentdetail
from django.contrib.auth.decorators import login_required

#These class views is for chating
    
class HomeView(TemplateView):
    template_name ='home/chat.html'
        
    def get(self, request):
        form =HomeForm()
        posts = Post.objects.all().order_by('created')
        users = User.objects.all()
        #exclude(id=request.user.id)
    
        friend = Friend.objects.get(current_user=request.user)
    
        friends = friend.users.all()
      
        args = {'form': form, 'posts': posts, 'users': users, 'friends':friends}
        #'friends':friends
        return render(request, self.template_name, args)
        
    def post(self,request):
        form =HomeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.user =request.user
            post.save()
            text = form.cleaned_data['post']
            
            
            form = HomeForm()
            return redirect('home:chat')
            
        args = {'form': form, 'text':text}
        return render(request, self.template_name, args)
        
@login_required
def activate(request):
        form = HomeForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            create = form.save()
            create.save
            
            return redirect('home:activatefriend')
            
        args = {'form': form}
        return render(request, 'home/activate.html', args)
@login_required
def activatefriend(request):
        form = FriendForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            create = form.save()
            create.save
            
            return redirect('home:authors')
            
        args = {'form': form}
        return render(request, 'home/activatefriend.html', args)



def home(request):
    context = {
       'categories':Item.objects.all() 
    }
    return render (request, "home/home.html", context)
 
def index(request):
    
    context = {
       'categories':Category.objects.all() 
    }
    return render(request, 'home/index.html', context)



def donate(request, item_id):
    try:
        itm = Item.objects.get(id=item_id)
    except Item.DoesNotExist:
        itm = None
        
    context = {
        'item': itm
    }

    return render (request, "home/donate.html", context)

def item(request, item_id):
    try:
        itm = Item.objects.get(id=item_id)
    except Item.DoesNotExist:
        itm = None
        
    context = {
        'item': itm
    }
    return render(request, 'home/item.html', context)

def category(request, category_id):
    try:
        catg = Category.objects.get(id=category_id)
    except Category.DoesNotExist:
        catg = None
    context = {
        'category': catg,
        'categories': Category.objects.all(),
        'count': Item.objects.filter(category=category_id).count()
    }
    return render(request, 'home/category.html', context)





#This view is for class registration- 
def register(request):
        form = ClassRegistration(request.POST or None)
        if form.is_valid():
            create = form.save()
            create.save
            
            return redirect('login')
            
        args = {'form': form}
        return render(request, 'home/create.html', args)
        
@login_required
def book(request, item_id):
    form = PostForm2(request.POST or None, request.FILES or None)
   
    if form.is_valid():
        create = form.save(commit=False)
        create.save()
            
        return redirect('home:payment', item_id)
            
    item = {'form': form}
        
    return render(request, 'home/book_request.html', item)

@login_required
def payment(request, item_id):
    try:
        itm = Item.objects.get(id=item_id)
    except Item.DoesNotExist:
        itm = None
        
    context = {'item': itm}

    return render (request, "home/payment.html", context)

def authors(request):
    return render (request, "home/authors.html", {})



def hasira(request):
    return render (request, "home/hasira.html", {})
def gis(request):
    return render (request, "home/gis.html", {})

def gispay(request):
    return render (request, "home/gispay.html", {})
def makala(request):
    return render (request, "home/makala.html", {})
@login_required
def bitcoin(request):
    return render (request, "home/bitcoin.html", {})

def matangazo(request):
    return render (request, "home/matangazo.html", {})
def mahesabu(request):
    return render (request, "home/mahesabu.html", {})

def uaminifu(request):
    return render (request, "home/uaminifu.html", {})
@login_required
def wito(request):
    return render (request, "home/wito.html", {})
@login_required
def english_book(request):
    return render (request, "home/english_intro.html", {})
@login_required
def lulu_book(request):
    return render (request, "home/lulu_book.html", {})

def gis_project(request):
    return render (request, "home/gis_project.html", {})
def nisome_kabla(request):
    return render (request, "home/nisome_kabla.html", {})
def myrefference(request):
    return render (request, "home/myrefference.html", {})




















#post_list      

     

home/templates/home/old/activatefriend.html
{% extends 'base2.html' %}

{% load staticfiles %}
<br><br>

   {% block body %}

<script>
	function go ()

{alert('if the answer is "No" make sure to highlight your customer username in Users, then click drop down button, select the same username in curent User');}

go();

</script>


     <br><br>
      
      
      
      
       <main class="page-wrapper">
		
			<div class= "container">
				

					
                                        
           
                <div class="text-center">
                <h1>ACTIVATE NEW USER</h1> 
                                                  
                  </div>   
        
                                                 
						 <hr>	    
		
                                       
                                       <br>
                   <div class="text-center">                     
             <p><span>CUSTOMER BOUGHT A BOOK FROM THIS SITE BEFORE?</span></p>
											</div>
											<hr>
				<div class="row">
							

								
<div class="col-md-5">

								<div class="alert alert-danger">
<button class="collapsible">NO</button>

<div class="content">
<br>
									<div class="form">
                                                                        
		<form method="POST" action ='' enctype='multipart/form-data'>
                               {% csrf_token%}
                               {{form.as_p}}
                             <button type="submit" class="btn btn-follow block btn-login">
							submit </button>
                      </form>                                                    
					</div>
							</div>
						
					</div>
	
</div>



<div class="col-md-5">
<div class="alert alert-danger">

<h2 class="collapsible" ><span><a href="{% url 'home:chat'%}" style="color:#fff;text-decoration:none;">YES</a></span></h2> 

</div>
</div>

</div>

</div>


	</main>



	<script>
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}
</script>



   {% endblock %}

home/templates/home/old/book_request.html
{% extends 'base2.html' %}
{% load staticfiles %}

   {% block body %}
         



      
      
      
      
       <main class="page-wrapper">
		<div class="page-header">
		</div><div class="jumbotron">
			<div class="page-conten container mt-50">
				<div class="row">

					
                                        
                                        <div class="col-md-12 col-sm-12">
                                                  <hr>
                                                 
                                                 <h2>Jaza Jina lako kamili na kitabu unachotaka kununua</h2> 
                                    
                                                 
						 <hr>  
					</div>
                                       
                                        <br><br>
                                        
                                        <div class="col-md-8">
						

						


						<div class="row">
							<div class="col-md-10 col-sm-12">
								<div class="alert alert-danger">
									<div class="form">
                                                                        <form method="post">

                                                                        {% csrf_token%}
                                                                        {{form.as_p}}
                                                                    
                                                                    
                                                            <button type="submit" class="btn btn-success block btn-login">
										 	Send </button>
                                                                            </form>





                                                                        
								</div>
							</div>
						</div>


								
							</form>
						</div>
					</div>



					<div class="col-md-4">
						
						  <img src="{%static 'accounts/img/logpic2.jpg'%}" class="img-responsive" alt=""'>
						<hr>


						<h3>
							<a href="http://gis4life.pythonanywhere.com/" target="_blank">GIS ONLINE</a> 
						</h3>

						<p>
							Become GIS pro within a short period of time.
						</p>
						<hr>



						<h3>
							Build your Empire
						</h3>

						<p class="mb-20">
							Are you an enterpreneur. Do you want to build your Empire? Contact us. Thanks
						</p>
						
					</div>
				</div>
			</div>
	</main>

   {% endblock %}

home/templates/home/old/chat.html
{% extends 'base2.html' %}
{% load staticfiles %}


  

   {% block body %}
        <br>
 
 
  <main class="page-wrapper">
   
                
			<div class="page-conten container mt-50">
        <div class="text-center">
                            <h3>Hi {{ user.first_name }}!</h3>
     </div>
     <br>
		<div class="intro mb-8"><span>LIPA KUONA KITABU</span></div>
              <hr><hr>
				<div class="row">
					<div class="col-md-7">
                   

      {% for post in posts%}

               {%if post.user in friends%}
               <!-- this is for authors only -->
                     <a href="{{post.booklink}}">{{post.booklink}} </a>                                                                        <br>                                           
                    <h3>Read: <a href="{{post.post}}">{{post.bookname}}</a></h3>
                                                               
           <br>
                                                                 
                                                                 
         {%endif%}
                                                                 
        {%endfor%}
</div>

                                    
                                       
                                        <div class="col-md-5">
                                    
        {%if user.userprofile.profilemake %}
   <h3>JENGA HIMAYA</h3>
       <div class="line-sep"></div>
   <h3><a href="{{user.userprofile.profilemake}}"> Activate</a> New Member</h3>
                                      
      


                 {%endif%}

{%if user.userprofile.backofice %}
   <h3>JENGA HIMAYA</h3>
       
   
                                      
      <h3><a href="{{user.userprofile.backofice}}">My Back office </a></h3>


                 {%endif%}



                     </div>


				 </div>
			   </div>

	</main>
        
        
        

   {% endblock %}

home/templates/home/old/gis.html
<!DOCTYPE html>
<html lang="en">
    
{% extends 'base2.html' %}
{% load staticfiles %}

{%block head%}
     
    
    
    {%endblock%}



 {% block body %}

	<main class="main-wrapper">
		
		
		





	<div class="main-section">
		<div class="container">
			<br><br>
			<h3>Muda wa kusoma GIS bure umeisha. Bofya 

				<a href="http://www.obgmycompany.com/home/item/2/">hapa</a> ili kulipia.</h3>

		</div>
	
</main>
     
     
      {% endblock %}   
        
       

home/templates/home/old/index.html
{% extends 'basebooks.html' %}

{% load static %}


   {% block body %}
        <br>  <br>  
        <section class="section">




	    <div class="container-fluid">
			 <div class="row">

          <div class="sidebar">
            <div class="side-bar">
              <ul class="cat-lists">
                <li><a href="{% url 'home:index' %}" class="active">Vitabu Vyote</a> </li>

                {% for category in categories %}
                <li><a href="{% url 'home:category' category_id=category.id %}">
                    {{category.name}}</a></li>
                {% endfor %} 
              </ul>
            </div>
          </div> 

<hr>
          <!-- main body -->

          <div class="col-md-8">
            {% for category in categories %}
            <div class="main-part">
              <div class="mp-title">
                 <hr>
                <h3>  
               
                  {{category.name}}
                </h3>

                <div class="mp-books-count">
                  <span>
                    <!-- 0 books -->
                  </span>
                </div>
              
              </div>


              <div class="mp-books">
                <div class="row">
                  
                 {%for item in category.item_set.all %}
                  <div class="">
                    <div class="card book-card">
                      <div class="book-body">
                        <div class="book-image">

<a href="{% url 'home:item' item_id=item.id %}">
                          <img src="{{item.image_index.url}}" alt="">
                          </a>
                        </div>

                              
                             
                      </div>
                    </div>
                  </div>

                 {%endfor%}

                  
                </div>
              </div>
            </div>
            {% endfor %}
          </div>


       </div>

            


             
            </div>
        </section>
        
        
     
      <br><br>

     
      


   {% endblock %}