accounts/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
#from django.contrib.auth import views as auth_views

# from django.contrib.auth.views import (
#     login,
#     logout,
#     password_reset,
#     password_reset_done,
#     password_reset_confirm,
#     password_reset_complete
# )

app_name='accounts'

urlpatterns = [


    path('', views.view_profile),
    path('signup/', views.signup, name='signup'),
    path('index', views.index, name='index'),
    path('entry/', views.entry, name = 'entry'),
    
    
    path('register/', views.register, name='register'),
   
    path('profile/', views.view_profile, name='view_profile'),
    path('activate/', views.activate, name='activate'),

   
    path('<int:profile_id>/', views.view_profile, name='view_profile_with_pk'),

    path('profile/edit/', views.edit_profile, name='edit_profile'),
    
]

himaya/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from himaya.views import *

app_name='himaya'

urlpatterns = [
    path('',views.home, name='home'),

    

    url(r'^urais_mikoa/$', views.urais_mikoa, name = 'urais_mikoa'),
    url(r'^urais_nchi/$', views.urais_nchi, name = 'urais_nchi'),
    url(r'^announcement/$', views.announcement, name = 'announcement'),


    url(r'^regions/$', views.regions, name= 'regions'),
    url(r'^get_regional_votes_geo/$', views.get_regional_votes_geo, name= 'get_regional_votes_geo'),

    url(r'^get_pres_votes_Geo/$', views.get_pres_votes_Geo, name= 'get_pres_votes_Geo'),
    url(r'^regcenter/$', views.regcenter, name= 'regcenter'),

    url(r'^districts/$', views.districts, name= 'districts'), 
    url(r'^constituency/$', views.constituency, name= 'constituency'), 
    url(r'^wards/$', views.wards, name= 'wards'),
    
    url(r'^wards_in_constituency/$', views.wards_in_constituency, name= 'wards_in_constituency'),
    url(r'^get_constituencies/$', views.get_constituencies, name= 'get_constituencies'),
    url(r'^get_R_constituency/$', views.get_R_constituency, name= 'get_R_constituency'),
    url(r'^get_C_wards/$', views.get_C_wards, name= 'get_C_wards'),
    
    url(r'^get_constituency/$', views.get_constituency, name= 'get_constituency'),
    
    url(r'^get_Const_Winners/$', views.get_Const_Winners, name= 'get_Const_Winners'),
    url(r'^get_C_wards_Winners/$', views.get_C_wards_Winners, name= 'get_C_wards_Winners'),
    url(r'^get_C_wards_View/$', views.get_C_wards_View, name= 'get_C_wards_View'),

    url(r'^get_R_constituency_View/$', views.get_R_constituency_View, name= 'get_R_constituency_View'),
    url(r'^get_R_village_View/$', views.get_R_village_View, name= 'get_R_village_View'),

    
    url(r'^PresVotesConst/$', views.PresVotesConst, name= 'PresVotesConst'),
     url(r'^get_presidential_const_votes_total/$', views.get_presidential_const_votes_total, name= 'get_presidential_const_votes_total'),


    # url(r'^tanzania/$', views.tanzania, name= 'tanzania'), 

    # url(r'^necgis/$', GisPageView.as_view(), name = 'necgis'),

    # url(r'^results/$', ResultsPageView.as_view(), name = 'results'),


    # url(r'^urais/$', UraisView.as_view(), name = 'urais'),
    # url(r'^ubunge/$', UbungeView.as_view(), name = 'ubunge'),


    # url(r'^between/$', BetweenAd.as_view(), name = "between"),
    # url(r'^othermaps/$', othermaps.as_view(), name = "othermaps"),

    # url(r'^region_data/$', region_datasets, name = 'region_data'),
    # url(r'^regcenter_data/$', regcenter_datasets, name = 'regcenter_data'),



    
    
      
]

home/urls.py






from django.conf.urls import url
from django.urls import path, re_path
from . import views
from home.views import HomeView

app_name='home'

urlpatterns = [

    path('', views.index),
    
    
    path('chat', HomeView.as_view(), name = 'chat'),
    
    path('home/', views.home, name = "home"),
    path('index/', views.index, name = "index"), 
 
    
    re_path(r'^item/(?P<item_id>\d+)/$', views.item, name = "item"),
    re_path(r'^item/(?P<item_id>\d+)/book/$', views.book, name = "book"),
    re_path(r'^item/(?P<item_id>\d+)/payment/$', views.payment, name = "payment"),
    re_path(r'^item/(?P<item_id>\d+)/donate/$', views.donate, name = "donate"),
    


    path('activate/', views.activate, name = "activate"),
    path('activatefriend/', views.activatefriend, name = "activatefriend"),

    path('makala/', views.makala, name = "makala"),
    path('authors/', views.authors, name = "authors"),
    

    re_path(r'^category/(?P<category_id>\d+)/$', views.category, name = "category"),

    path('hasira/', views.hasira, name = "hasira"),
    path('gis/', views.gis, name = "gis"),
    path('myrefference/', views.myrefference, name = "myrefference"),

    path('gispay/', views.gispay, name = "gispay"),
    path('bitcoin/', views.bitcoin, name = "bitcoin"),
    path('matangazo/', views.matangazo, name = "matangazo"),
    path('mahesabu/', views.mahesabu, name = "mahesabu"),
    path('uaminifu/', views.uaminifu, name = "uaminifu"),
    path('english_book/', views.english_book, name = "english_book"),
    path('lulu_book/', views.lulu_book, name = "lulu_book"),
    path('gis_project/', views.gis_project, name = "gis_project"),
    path('wito/', views.wito, name = "wito"),
    path('nisome_kabla/', views.nisome_kabla, name = "nisome_kabla"),
    


    path('register/', views.register, name = "register"),
    
      
]

mysite/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import  admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import ItemSitemap,ViewSitemap
from accounts.sitemaps import StaticViewSitemap
sitemaps = {
    
    'static': StaticViewSitemap,
    'view':ViewSitemap,
    'snippet': ItemSitemap,
}

app_name='mysite'

urlpatterns = [
     path('', views.login_redirect, name='login_redirect'),
    
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include ('accounts.urls',namespace='accounts')),
    path('home/', include ('home.urls', namespace='home')),
    path('himaya/', include ('himaya.urls', namespace='himaya')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)               
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views 
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.urls import path, include
from django.contrib import  admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import ItemSitemap,ViewSitemap
from accounts.sitemaps import StaticViewSitemap
sitemaps = {
    
    'static': StaticViewSitemap,
    'view':ViewSitemap,
    'snippet': ItemSitemap,
}

app_name='mysite'

urlpatterns = [
     path('', views.login_redirect, name='login_redirect'),
    
    url(r'^sitemap\.xml/$', sitemap, {'sitemaps':sitemaps}),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include ('accounts.urls',namespace='accounts')),
    path('home/', include ('home.urls', namespace='home')),
    path('himaya/', include ('himaya.urls', namespace='himaya')),
   
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)               
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.

accounts/forms.py
from django import forms
from . import models
# from accounts.models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import  UserCreationForm, UserChangeForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)


    class Meta:
        model = User
        fields = ('username','first_name','last_name','email','password1','password2')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name','last_name','email','password')


class UserProfileForm(forms.ModelForm):
    Proffession= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Put activation code here....'
        }
    ))
    
    upliner= forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Put upliner name here....'
        }
    ))
    
    name = forms.CharField(widget=forms.TextInput(
        attrs={
            'class':'form-control',
            'placeholder': 'Put new member name....'
        }
    ))
    
    class Meta:
        # s
        fields=('user','Proffession','name','upliner', 'Maelezo', 'phone', 'image')

accounts/views.py
from django.shortcuts import render, redirect,reverse
from django.http import HttpResponse, HttpResponseRedirect
from .forms import (
    RegistrationForm,
    EditProfileForm,
    UserProfileForm,
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


def signup(request):
    if request.method =='POST':
      form = UserCreationForm(request.POST)
      if form.is_valid():
        form.save()
        return redirect (reverse('accounts:entry'))
    else:
      form = UserCreationForm()
    return render (request, 'accounts/signup.html', {'form':form})

def index(request):
    return render (request, "accounts/gis.html", {})


def entry(request):
    template = 'accounts/entry.html'
    context = {}
    return render (request, template, context)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            #return redirect('/account')
            return redirect(reverse('home:register'))
    else:
        form = RegistrationForm()

    args = {'form': form}
    return render(request, 'accounts/reg_form.html', args)
        
def view_profile(request, pk=None):
    args = {'user': request.user}
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args ={'user': user}
    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect (reverse('accounts:view_profile')) #('/account/profile')
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)




    
def activate(request):
        form = UserProfileForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            create = form.save()
            create.save
            
            return redirect('home:chat')
            
        args = {'form': form}
        return render(request, 'accounts/activate.html', args)
        

accounts/templates/accounts/activate.html
{% extends 'base2.html' %}

{% load static %}
<br><br>

   {% block body %}
     <br><br>
      
      
      
      
       <main class="page-wrapper">
		<div class="page-header">
		</div>
			<div class="page-conten container mt-50">
				<div class="row">

					
                                        
           <div class="col-md-12 col-sm-12">
                <h2>Activation Form</h2> 
                                                  <hr>
                    <div class="line-sep"></div>  
        <p>This form must be filled with the help of your <span>upliner</span>.</p>
                                                 
						 <hr>	    
					</div>
                                       
                                        <br><br>
                                        
             <div class="col-md-6">
					
				<div class="row">
							<div class="col-md-10 col-sm-12">
								<div class="alert alert-danger">
									<div class="form">
                                                                        
		<form method="POST" action ='' enctype='multipart/form-data'>
                               {% csrf_token%}
                               {{form.as_p}}
                             <button type="submit" class="btn btn-follow block btn-login">
							submit </button>
                      </form>                                                    
					</div>
							</div>
						</div>
	

								
				<div class="col-md-10 col-sm-12">
										<hr>
	
                 <p><a href="{% url 'reset_password'}">I forgot my Password &raquo;</a></p>
								      <hr>
									</div>
								<!--</div>-->
							
						</div>
					</div>



					<div class="col-md-6">
						
						  <img src="{%static 'img/logpic2.jpg'%}" class="img-responsive" alt=""'>
						<hr>


						<h3>
							<a href="http://gis4life.pythonanywhere.com/" target="_blank">GIS ONLINE</a> 
						</h3>

						<p>
							Become GIS pro within a short period of time.
						</p>
						<hr>



						<h3>
							Read Books
						</h3>

						<p class="mb-20">
							Do you believe in knowledge. buy books here.
						</p>
						
					</div>
				</div>
			</div>
	</main>
   {% endblock %}

accounts/templates/accounts/entry.html
{% extends 'base2.html' %} 
{% load static %}
    {%block head%}
     
    {% if item != None %}
        <title>{{item.name}}-Selected Class</title>
        
    {% else %}
        <title>Invalid Item ID- Selected Class</title>
    {% endif %}
    
    {%endblock%}


   {% block body %}
  
  


      
          <br> 
  
        
        <section class="section grey-scale">
      <div class="container">
<div class="col-lg-12 col-md-12">
  <div class="col-lg-12 col-md-12" style="padding-left: 0;padding-right: 0;">
  
                 
 <h2 class="btn btn-follow" ><span><a href="{% url 'home:index'%}" style="color:#fff;text-decoration:none;">Nunua Soma mtandaoni (ebook)</a></span></h2>
 <h2 class="btn btn-follow" ><span><a href="{% url 'accounts:index'%}" style="color:#fff;text-decoration:none;">Nunua vilivyo chapishwa (Hard copy)</a></span></h2>

  <h2 class="btn btn-follow" ><span><a href="{% url 'home:activate'%}" style="color:#fff;text-decoration:none;">Kwa Wandishi wauzaji</a></span></h2>
  <h2 class="btn btn-follow" ><span><a href="{% url 'himaya:urais_nchi'%}" style="color:#fff;text-decoration:none;">Locations</a></span></h2>

  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#regprocess">Namna ya kununua kitabu mtandao
                    </button> 

  <button type="button" class="btn btn-info" data-toggle="modal" data-target="#regprocess2">Namna ya kununua vitabu chapishwa
                    </button> 


            </div>
          </div>
        <div class="course-image bottom-in">
                
<img src="{%static 'accounts/img/safront3.jpg'%}" class="img-responsive" alt=""'> 
                
            </div>
        
        
      </div>
        
        </section>
        
        
        
        
        <section id="vedio-sec" style="background-color: #fff;">
      
          <div class="container">
          
                                
          
<div class="col-lg-12 col-md-12  col-sm-12 contnthere" style="margin-bottom: 15px;">
               

                <hr>
                <br>
<h3><span>OBG Company Limited.</span> </h3>

<p>Website hii inamilikiwa na kufanya kazi chini ya Kampuni ya "OBG Company Limited". Hii ni moja ya website chache maarufu nchini Tanzania ambayo inamuwezesha muandishi kufikisha vitabu kwa wasomaji popote pale duniani. Katika Website hii Muandishi ana options mbili; moja, kuuza kwa njia ya mtandao peke yake<span>(ebook)</span> au kuuza kwa njia ya kupakua <span>(Download)</span>. Wasiliana nasi kwa maelezo zaidi.</p>

<p>Website hii inawezesha watu wengi, haswa wale  wanaozungumza lugha ya Kiswahili, kupata vitabu na nakala mbali mbali kwa ajili ya kusoma kwa lengo la kujielimisha na kujiburudisha.</p>









</div></div></section>





              


<section class="section">
      <div class="container">
        <div class="row">

          <div class="col-md-12"style="margin-bottom: 15px;">
             
              <h3><span>Wasiliana Nasi.</span></h3>
            
          </div>




          <div class="col-md-7">
            
                        
                                           
                    <div id="contact">
                                    
                    
                        <div class="video-container">                                   
   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5233.185493903763!2d39.27138706048278!3d-6.833484473017059!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x185c4ba5bbc1ba7b%3A0x2f4f0a88e2089417!2sKariakoo%2C+Dar+es+Salaam!5e0!3m2!1sen!2stz!4v1538828227060" frameborder="0" style="border:0" allowfullscreen></iframe>
                        </div>
                        
                    </div>
          </div>

<br>
          <div class="col-md-5">
            <div class="">
    <div><p>Tupigie simu <a href="tel:0653397942" class="pull-right">+255653397942</a></p></div>
                        
  
                            <hr>
        <p class="text-center">Or <br> be classical</p>
                       
  <form>
    <div class="form-group"><input type="text" class="form-control" name="" value="" placeholder="Name"></div>
                                                                
    <div class="form-group"><input type="email" class="form-control" name="" value="" placeholder="E-mail"></div>
                                                                
    <div class="form-group"><input type="tel" class="form-control" name="" value="" placeholder="Phone"></div>
                                                                
    <div class="form-group"><textarea class="form-control" name="" rows="3" placeholder="Message"></textarea></div>
                                                                
     <button class="btn btn-follow pull-right" type="submit" name="button">
           <i class="fa fa-paper-plane-o" aria-hidden="true"></i> Tuma</button>
  </form>
                        </div>
          </div>
        </div>
      </div>
    </section>
<br>
     
  </main>






 <div class="modal fade bd-example-modal-lg" id="regprocess" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
        <div class="modal-header">
       <h5 class="modal-title" id="exampleModalLongTitle">Hatua za kununu kitabu</h5>
       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                
                                            <!--<div class="modal-body">-->
                                            
             <ul class="courses-lists " align="left">
                                            
           <li><p>1.Bonyeza nunua vitabu </p></li>
           <li><p>2. Kutoka kwenye listi ya vitabu, chagua kitabu unachokitaka kisha bonyeza kwenye picha ya kitabu.</p></li>
                                                
                                         
            <li><p>3. Maelezo ya kitabu husika yatafunguka, utaona maelezo ya kitabu kwa ufupi, utapata maelezo kuhusu muandishi, utapata video fupi pamoja na bei ya kitabu husika</p></li> 
                                                
          <li><p>5. Bonyeza neno lipa kupata kurasa ya malipo.Kama ni mara yako ya kwanza (haujawahi kusajiliwa) utapelekwa kwenye eneo la kujisajili kisha kujaza fomu kuonyesha kitabu unachokitaka. Kama umeshajisajili awali utapelekwa kwenye fomu kujaza taarifa za kitabu </p></li>
         <li><p>6.  Baada ya hapa utapatiwa taarifa za malipo kwenda kwa muandishi wa kitabu husika. Fanya malipo kisha subiri kitabu chako kufunguka.</p></li>
         <li><p>7. Baada ya muda mchache kitabu chako kitafunguka, ili kukiona na kuweza kukisoma utabonyeza neni vitabu vyangu.</p></li>
         <li><p>7. Kama utasubiri zaidi ya dakika kumi na tano bila kukiona kitabu basi wasiliana na muandishi kwa namba utakayoiona kwenye kurasa ya malipo.</p></li>
         
                                                </ul> 
                                               
                                                    
                                                
                                                    
                                                    
                                           
              
                            </div>
                        </div>
                    </div>


  

        <div class="modal fade bd-example-modal-lg" id="regprocess2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
        <div class="modal-header">
       <h5 class="modal-title" id="exampleModalLongTitle">Hatua za kununu kitabu mtandao</h5>
       <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                
                                            <!--<div class="modal-body">-->
                                            
             <ul class="courses-lists " align="left">
                                            
           <li><p>1.Tuma mahitaji yako kwenye whatsapp namba 0653397942</p></li>
           <li><p>2. Tuma listi ya vitabu unavyovihitaji ukionyesha jina la kitabu na idadi ya vitabu.</p></li>
                                                
                                         
            <li><p>3. Kupata listi ya vitabu vinavyopatika kwetu, bonyeza "nunua vitabu chapishwa" hapo juu</p> </li> 
                                                
          <li><p>5. Wasiliana nasi kwa namba 0653397942 kwa ajili ya malipo na maelezo zaidi kama vile namna utakavyo pokea mzigo wako </p></li>
         <li><p>6. Tunasafirisha mizigo popote nchini, gharama za usafiri zinabadilika kutokana na eneo husika</p></li>
         
         
                                                </ul> 
                                               
                                                    
                                                
                                                    
                                                    
                                           
              
                            </div>
                        </div>
                    </div>






              
          
          
            
      </div>
    </div>
      
    </section>




    <footer>
    <div class="footer">
      <div class="container">
        
        <div class="row">
          <div class="col-md-4">
            <div class="link-title">
              <p>
                Kuhusu sisi
              </p>
              <div class="separator"></div>
            </div>


            <div>
              <p>
                <p> Sisi ni kampuni yenye malengo ya kubadili maisha ya watu kwa njia ya vitabu. </p>
              </p>
            </div>
          </div>


          <div class="col-md-2">
            

            <ul class="links">
              <div class="link-title">
              <p>
                kurasa
              </p>
              <div class="separator"></div>
            </div>
                                                        
                                                        <li>
                <a href="{% url 'home:index'%}">Listi ya vitabu</a>
              </li>

              <li>
                <!-- <a href="">Privacy Policy</a> -->
              </li>
            </ul>
          </div>

          
          <div class="col-md-3">
            <div class="link-title">
              <p>
                Zaidi
              </p>
              <div class="separator"></div>
            </div>

            <ul>
                                                    
                                                        
                
                       
                          
              
 
              
                <P><a href="{% url 'home:authors'%}">Tangaza nasi kitabu chako</a></P>
              
            </ul>
          </div>


          <div class="col-md-3">
            <div class="link-title">
              <p>
                Wasiliana nasi
              
              </p>
              <div class="separator"></div>
            </div>

            <p>
              3rd Floor, Imalaseko Investment Limited, <br>
              Kariakoo <br>
              P. O. Box 123 <br>
              Dar Es Salaam, Tanzania
            </p>
            <a href="tel:+255652441424" class="a-link">
              (+255) 653 397942
              
            </a>

            <a href="mailto:obmsuya@yahoo.com" class="a-link">
              obgcompanyltd@gmail.com
            </a>

          </div>


        </div>

        
          <hr class="white">
<hr class="white">

          <div class="footer-bottom">
            <span>
              @2018 OBG
            </span>

            <span>
              
            </span>
          </div>
                                        
                                        
                                        
                                     
                                        
                                        
      </div>
  </div>
    </footer>


  <script>
      function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
  </script>
 {% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base2.html' %}

{% load static %}

{%block head%}
     
    
    
{%endblock%}



   {% block body %}
      
      






<br><br><br><br><br><br>
 
 <main class="page-wrapper">
		<div class="page-header">
		</div>
			<div class="page-conten container mt-50">
				<div class="row">

					<div class="col-md-6">
						<div class="mb-8">
							<h2 class="auth-title">
								Register here
							</h2>
							<div class="line-sep"></div>
						</div>


						<div class="intro mb-8">
							Your password must be eight characters or more
						</div>


						<div class="row">
							<div class="col-md-10 col-sm-12">
								<div class="alert alert-danger">
									<div class="form">
                                                                        <form method="post">

                                                                        {% csrf_token%}
                                                                        {{form.as_p}}
                                                                    <!--<button type="submit">submit</button>-->
                                                                    
                                                            <button type="submit" class="btn btn-follow block btn-login">
										 	Submit </button>
                                                                            </form>
                                                                        
								</div>
							</div>
						</div>





						
							

								<div class="row">
									<div class="col-md-10 col-sm-12 mb-8">
										<hr>
										<p>
											Have an account? 
										<small><span class="caps"><a class="btn btn-clear "href="{% url 'accounts:index'%}" role="button">LogIn &raquo;</a></span></small>
										</p>
									</div>
								</div>
							</form>
						</div>
					</div>



					<div class="col-md-6">
						
						 <img src="{%static 'img/safront9.jpg'%}" class="img-responsive" alt=""'>
						<hr>


						<h3>
							<a href="http://gis4life.pythonanywhere.com/" target="_blank">GIS ONLINE</a> 
						</h3>

						<p>
							Become GIS pro within a short period of time.
						</p>
						<hr>




						<h3>
							Build your Empire
						</h3>

						<p class="mb-20">
							Are you an enterpreneur. Do you want to build your Empire? Contact us. Thanks
						</p>
						
					</div>
				</div>
			</div>
	</main>                         
    
  
   {% endblock %}